[tools]
go = "latest"
lua-language-server = "latest"
node = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
pnpm = "latest"
python = "latest"
stylua = "latest"
uv = "latest"
